.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/task.md, .github/workflows/build_ci.yml, .releaserc.yml
Configure the GitHub Actions to build, test and release the project.
=> ci: Configure the GitHub Actions

src/cli/logs.rs, src/cli/start.rs, src/config.rs, src/docker_compose.rs
#10 
Add MongoDB management for the new data system
=> feat: Add the mongo service in the docker-compose

src/cli/init.rs, src/cli/mod.rs
#__ 
Add the `lenra init` command to generate only `.lenra/` files. This will be useful for the `server` repository CI.
=> feat: Add command for dockerfile generation

Cargo.lock
Closes #34 
Update Dofigen dependency (and the other dependencies).
=> fix(deps): Dofigen update

src/cli/build.rs, src/cli/init.rs, src/cli/start.rs, src/config.rs, src/docker_compose.rs
=> feat: add expose options

README.md, src/cli/build.rs, src/cli/dev.rs, src/cli/logs.rs, src/cli/mod.rs, src/cli/start.rs
#19 
Add the dev command with it basic implementation: build, start and logs(app).
=> feat: Create the dev sub-command

src/config.rs
=> feat: remove timeout

src/cli/interactive.rs
Closes #24 
Stops the interactive command loop and the docker compose containers
=> feat: Interactive stop command

src/docker_compose.rs
Closes #47
Wait for https://github.com/lenra-io/dev-tools/pull/159
=> feat: add devtool healthcheck

src/docker_compose.rs
=> feat: MongoDB URL to HOSTNAME

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, README.md
Adapt the README to make the Lenra CLI the main repo
=> docs: Set the lenra_cli the main repo

src/config.rs, src/docker_compose.rs
Let the config override the Docker images of the app and services
=> feat!: Docker images in dev config

src/config.rs
Add suppress_lock env with the value true for http mode.
This let the server create the file when it's ready.
=> feat: suppress_lock for http mode

.github/workflows/build_ci.yml, Cargo.lock, Cargo.toml, README.md, src/docker.rs, src/docker_compose.rs, src/git.rs, src/main.rs
Closes #18 
Normalize the branch name to use it as image tag.
=> fix: Normalize image tag

Cargo.lock, Cargo.toml
Reverts lenra-io/lenra_cli#207
=> Revert "build(deps): bump async-trait from 0.1.61 to 0.1.68"

.github/FUNDING.yml
=> docs: Funding button

src/cli/upgrade.rs, src/git.rs, src/template.rs
=> fix: Template clone and upgrade

Cargo.lock, Cargo.toml, docs/commands/index.md, docs/commands/new.md, docs/index.md, src/cli/mod.rs, src/cli/new.rs, src/cli/upgrade.rs, src/errors.rs, src/git.rs, src/github.rs, src/main.rs, src/template.rs
Closes #218 
Find Lenra templates from topics anywhere on GitHub instead of only in the Lenra organization.
The management of the topics and the URL was not easy we might find a better solution later with arg groups for example.
=> feat!: Use topics to list Lenra templates en GitHub

src/docker_compose.rs
Closes #302 
Expose the fake OAuth2 port 4444.
=> feat: Expose oauth port

.github/workflows/build_ci.yml, install.md
Closes #305 
I changed the CI to not zip the artifact before uploading it, and make it renamed directly to the platform name.
This also fix the checkout:v2 deprecation warning.
Fork the project and commit something on the beta branch.
The publish step must failed with error : `v1.0.0-beta.1 already exist.`
=> ci: upload artifacts without zipping it

src/cli/logs.rs, src/cli/upgrade.rs, src/command.rs, src/docker_compose.rs, src/errors.rs, src/git.rs, src/lenra.rs, src/template.rs
Closes #275 
Refactor the commands call management to handle errors and StdIO in a better way.
Install the CLI:
```bash
cargo install --path .
```
In a Lenra app project, add a failing command in the Dockerfile (or dofigen) and then run the dev command:
```bash
lenra dev
```
=> fix: Better command launch management

Cargo.lock, src/config.rs, src/docker_compose.rs
Closes #359 
Allow defining the devtool log level in the dev section of the `lenra.yml` file:
```yaml
dev:
devtool:
logLevel: debug
```
If not defined will use the default value: `info` (defined if the devtool itself).
- Build the CLI
- add the upside YAML lines to the `lenra.yml` of a project
- run the net lines and you should see some debug logs:
```bash
lenra build
lenra start
lenra logs -f devtool
```
=> feat: Manage devtool log level

Cargo.lock, src/cli/dev/interactive.rs, src/cli/mod.rs, src/config.rs
Closes #400 
Other deps have been upgraded too
=> feat: Upgrade Dofigen and other libs

src/cli/build.rs, src/cli/mod.rs, src/cli/new.rs, src/cli/start.rs, src/cli/stop.rs, src/cli/update.rs
Closes #399 
Run the Lenra CLI in dev mode and see if there is unwanted logs:
```
lenra dev -v > log.txt
```
=> feat: No animation on verbose commands
